import { Level } from './types';

export const LEVELS: Level[] = [
  {
    id: '1',
    cols: 5,
    rows: 3,
    start: { x: 0, y: 1, dir: 1 },
    goal: { x: 4, y: 1 },
    walls: [],
    par: 4,
    intro:
      'Encadena comandos y dale a Ejecutar. La ruta corre entera de golpe: no puedes corregir a mitad.',
  },
  {
    id: '2',
    cols: 4,
    rows: 4,
    start: { x: 0, y: 3, dir: 1 },
    goal: { x: 3, y: 0 },
    walls: [],
    par: 7,
    intro:
      'Avanzar va en la dirección que mira el dron. Para subir, antes tendrás que girar.',
  },
  {
    id: '3',
    cols: 5,
    rows: 3,
    start: { x: 0, y: 1, dir: 1 },
    goal: { x: 4, y: 1 },
    walls: [[2, 1]],
    par: 10,
    intro:
      'Hay un bloque en medio. Planéalo en tu cabeza antes de ejecutar: si chocas, vuelves al inicio.',
  },
  {
    id: '4',
    cols: 5,
    rows: 5,
    start: { x: 0, y: 4, dir: 0 },
    goal: { x: 4, y: 4 },
    walls: [
      [1, 1],
      [2, 1],
      [3, 1],
      [1, 2],
      [2, 2],
      [3, 2],
      [1, 3],
      [2, 3],
      [3, 3],
    ],
    par: 14,
    intro:
      'Rodea el edificio. Cuantos menos comandos uses, mejor: intenta igualar el par.',
  },
  {
    id: '5',
    cols: 5,
    rows: 5,
    start: { x: 0, y: 0, dir: 1 },
    goal: { x: 4, y: 4 },
    open: [
      [0, 0],
      [1, 0],
      [2, 0],
      [3, 0],
      [4, 0],
      [4, 1],
      [0, 2],
      [1, 2],
      [2, 2],
      [3, 2],
      [4, 2],
      [0, 3],
      [0, 4],
      [1, 4],
      [2, 4],
      [3, 4],
      [4, 4],
    ],
    par: 20,
    intro:
      "Un pasillo en zigzag. Toca repetir 'avanzar' muchas veces… fíjate en lo cansino que se vuelve.",
    outro:
      '¿Te has fijado? Has escrito «avanzar» una y otra vez. En el próximo mundo desbloquearás los BUCLES: decir «repite 4 veces» en lugar de copiar y pegar. Justo eso que acabas de echar de menos.',
  },
  // ---- Mundo 2: BUCLES ----
  {
    world: 2,
    id: 'w2-1',
    cols: 8,
    rows: 5,
    start: { x: 0, y: 2, dir: 1 },
    goal: { x: 7, y: 2 },
    walls: [],
    budget: 3,
    par: 2,
    intro:
      "¿Otra vez a base de 'avanzar, avanzar, avanzar'? Ahora tienes REPETIR. Prueba.",
    solution: [{ type: 'loop', times: 7, body: [{ type: 'move' }] }],
  },
  {
    world: 2,
    id: 'w2-2',
    cols: 5,
    rows: 5,
    start: { x: 0, y: 4, dir: 1 },
    goal: { x: 4, y: 0 },
    open: [
      [0, 4],
      [1, 4],
      [1, 3],
      [2, 3],
      [2, 2],
      [3, 2],
      [3, 1],
      [4, 1],
      [4, 0],
    ],
    budget: 6,
    par: 5,
    intro:
      'El pasillo que te torturó… ¿lo reconoces? Fíjate en el patrón que se repite.',
    solution: [
      {
        type: 'loop',
        times: 4,
        body: [
          { type: 'move' },
          { type: 'turn', dir: 'L' },
          { type: 'move' },
          { type: 'turn', dir: 'R' },
        ],
      },
    ],
  },
  {
    world: 2,
    id: 'w2-3',
    cols: 4,
    rows: 2,
    start: { x: 0, y: 0, dir: 1 },
    goal: { x: 3, y: 1 },
    open: [
      [0, 0],
      [1, 0],
      [2, 0],
      [3, 0],
      [3, 1],
    ],
    budget: 4,
    par: 4,
    intro: 'Cuidado: si repites de más, chocas. Cuenta bien cuántas veces.',
    solution: [
      { type: 'loop', times: 3, body: [{ type: 'move' }] },
      { type: 'turn', dir: 'R' },
      { type: 'move' },
    ],
  },
  {
    world: 2,
    id: 'w2-4',
    cols: 3,
    rows: 3,
    start: { x: 0, y: 2, dir: 1 },
    goal: { x: 0, y: 0 },
    open: [
      [0, 2],
      [1, 2],
      [2, 2],
      [2, 1],
      [2, 0],
      [1, 0],
      [0, 0],
    ],
    budget: 5,
    par: 4,
    intro: 'El patrón ahora es más largo. Métele varios comandos al bucle.',
    solution: [
      {
        type: 'loop',
        times: 3,
        body: [{ type: 'move' }, { type: 'move' }, { type: 'turn', dir: 'L' }],
      },
    ],
  },
  {
    world: 2,
    id: 'w2-5',
    cols: 6,
    rows: 3,
    start: { x: 0, y: 0, dir: 1 },
    goal: { x: 5, y: 2 },
    open: [
      [0, 0],
      [1, 0],
      [2, 0],
      [3, 0],
      [4, 0],
      [5, 0],
      [5, 1],
      [5, 2],
    ],
    budget: 5,
    par: 5,
    intro:
      'Un bucle para el pasillo… y unos comandos sueltos al final para llegar. Se pueden combinar.',
    solution: [
      { type: 'loop', times: 5, body: [{ type: 'move' }] },
      { type: 'turn', dir: 'R' },
      { type: 'move' },
      { type: 'move' },
    ],
  },
  // DEBUG — nivel temporal para probar el pintado de bucles. Eliminar antes del MVP.
  {
    id: 'debug-loop',
    cols: 5,
    rows: 3,
    start: { x: 0, y: 1, dir: 1 },
    goal: { x: 4, y: 1 },
    walls: [],
    par: 1,
    intro: '[DEBUG] Programa pre-cargado con bucles. Solo para ver el pintado en CommandStrip.',
  },
];
